version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ./init:/docker-entrypoint-initdb.d
# https://hub.docker.com/_/mysql
